M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Wed Oct 11 21:50:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-11T21:50:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X86.46Y-125.5
T2
X79.56Y-63.5
X79.6Y-43.0
X79.6Y-84.05
X88.36Y-63.5
X88.4Y-43.0
X88.4Y-84.05
T3
X90.5Y-96.0
T0
M30
