M48
; DRILL file {KiCad 6.0.10+dfsg-1~bpo11+1} date Sat Feb 18 13:34:48 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-18T13:34:48+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X86.46Y-125.5
T2
X79.56Y-63.5
X79.6Y-43.0
X79.6Y-84.05
X88.36Y-63.5
X88.4Y-43.0
X88.4Y-84.05
T0
M30
