M48
; DRILL file {KiCad 7.0.1.1-36-gbcf78dbe24-dirty-deb11} date Sun Apr  9 19:21:00 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-09T19:21:00+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1.1-36-gbcf78dbe24-dirty-deb11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X68.0Y-96.0
T0
M30
